# Generated by Django 4.2.1 on 2023-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_web_cam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='is_archive_avaliable',
            field=models.BooleanField(default=False, help_text='Доступ к архиву', verbose_name='Доступ к архиву'),
        ),
    ]
