# Generated by Django 4.2.1 on 2023-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_web_cam', '0002_alter_advuser_is_archive_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='tel_number',
            field=models.IntegerField(help_text='Введите мобильный телефон', null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='test_period_until',
            field=models.DateTimeField(help_text='Тестовый период до', null=True, verbose_name='Дата окончания тестового периода'),
        ),
    ]
