# Generated by Django 4.2.1 on 2023-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_web_cam', '0003_alter_advuser_tel_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Аккаунт прошел активацию', verbose_name='Активирован'),
        ),
    ]
