# Generated by Django 4.2.1 on 2023-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_web_cam', '0004_advuser_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.CharField(help_text='Описание положения камеры', max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
